// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugleimgaegkvvxupqqmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbGVpbWdhZWdrdnZ4dXBxcW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzA0MTcsImV4cCI6MjA2NjQwNjQxN30.NZ3Kr_uWqm7Pu0JCcqpyJJ5Zd0-mvzHWXkOK2xunFdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);